[package]
name = "magpie"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "*"
itertools = "0.11.0"
num_cpus = "1.16.0"
rpassword = "7.2"
scraper = "0.17.1"
strum = "*"
strum_macros = "0.25.3"

[dependencies.polars]
version = "0.34.2"
features = ["lazy", "temporal"]

[dependencies.reqwest]
version = "0.11"
features = ["blocking", "cookies", "json"]