[package]
name = "magpie-bird"
version = "0.4.2"
authors = ["DanielMorton <dacmorton@gmail.com>"]
description = "eBird Target Bird Scraper"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DanielMorton/magpie"
edition = "2021"
exclude = [
    ".idea/*",
    "magpie.iml"
]

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
rayon = "1.11.0"
rpassword = "7.4.0"
scraper = "0.24.0"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.16"

[dependencies.indicatif]
version = "0.18.0"
features = ["rayon"]

[dependencies.polars]
version = "0.42.0"
features = ["diagonal_concat", "lazy", "temporal"]

[dependencies.reqwest]
version = "0.12.23"
features = ["blocking", "cookies", "json"]