version: 2.2
jobs:
  build:
    docker:
      - image: cimg/rust:1.80.1
    steps:
      - checkout
      - run: cargo build
  build:
    docker:
      - image: cimg/rust:1.81.0
    steps:
      - checkout
      - run: cargo build
