version: 2.1
jobs:
  build:
    parameters:
      rust-image:
        type: string
    docker:
      - image: cimg/rust:<< parameters.rust-image >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.lock" }}
      - run: cargo build --all-targets
      - run: cargo test
      - save_cache:
          key: cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - target

workflows:
  build-and-test:
    jobs:
      - build:
          matrix:
            parameters:
              rust-image: ["1.96.0", "1.97.0"]
