version: 2.1
jobs:
  build:
    parameters:
      rust-image:
        type: string
    docker:
      - image: cimg/rust:<< parameters.rust-image >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.lock" }}
      - run: cargo build --all-targets
      - run: cargo test
      - save_cache:
          key: cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo/registry
            - target

workflows:
  build-and-test:
    jobs:
      - build:
          matrix:
            parameters:
              rust-image: ["1.76.0", "1.77.0", "1.78.0", "1.79.0", "1.80.0", "1.81.0", "1.82.0", "1.83.0", "1.84.0", "1.85.0", "1.86.0", "1.87.0", "1.88.0", "1.89.0", "1.90.0", "1.91.0", "1.92.0", "1.93.0", "1.94.0", "1.95.0", "1.96.0", "1.97.0"]
